(function(){var f;var h=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},k=function(a){if(h(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&h(a))return a;return null},m=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},p=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a},v=function(a,b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)};var y=function(a,b){return a.x*b.x+a.y*b.y},B=function(a,b){return z(b,y(a,b))},z=function(a,b){return C(a.x*b,a.y*b)},C=function(a,b){return{x:a,y:void 0!==b?b:a}};var D=function(a,b){function c(){}c.prototype=b.prototype;a.C=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Fa=function(a,c,q){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var E=["-ms-","-moz-","-webkit-",""],G=function(a,b,c){for(var d,e,q=0;q<E.length;++q)d=E[q]+b,e=""+c,a.style.setProperty(d,e)};var H=function(a,b,c){if(c){var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c)}else d=document.createEvent("Event"),d.initEvent(a,!0,!0);b.dispatchEvent(d);return d},aa=function(a,b){setTimeout(function(){H("autoplayended",a,b)},0)},ba=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var ca=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var da=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},J=function(a,b){this.m=a;this.s=null;this.Ea=b;this.M=!1};
J.prototype.play=function(a,b,c){if(this.m.frameCount&&null==this.s){b=b||"forwards";if(c){var d=Math.floor(a/c);a=c}else d=this.m.frameCount,a/=d;var e=[],q=da(this.m);c=q;for(var n=0;n<d;n++){if(0<n||!this.Ea)c=K(c+L(b,1),this.m.frameCount);e.push(c)}b=function(){if(e.length){var a=e.shift();this.M=!0;this.m.goToFrame(a+1);this.M=!1;var b=this.m;H("frameautoplayed",b,{id:a+1||b.currentIndex})}else this.stop(!0),this.m.goToFrame(q+1)}.bind(this);this.s=setInterval(b,a);setTimeout(b)}};
J.prototype.stop=function(a){!this.M&&this.s&&(clearInterval(this.s),aa(this.m,{completed:!!a}),this.s=null)};
var ea=function(a){var b=document.createElement("img","gwd-image");b.setAttribute("source",a);return b},M=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(ea(ca(a[c])))}return b},N=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];"img"==e.tagName.toLowerCase()&&"gwd-image"==e.getAttribute("is")&&(null!=b?e.setAttribute("scaling",b):e.removeAttribute("scaling"))}},fa=function(a,b){var c=b.length;b=b.splice(0,c);for(var d,e=0;e<c;e++)d=b[e],"frameshown"==
d?H(d,a,{id:a.currentIndex}):H(d,a)},L=function(a,b){return"left"==a||"backwards"==a?-b:b},K=function(a,b){return(a%b+b)%b},ga=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.pause()})},ha=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio")).forEach(function(a){a.play()})};var O=function(){};D(O,HTMLElement);f=O.prototype;f.createdCallback=function(){this.frames=[];this.a=null;this.b=0;this.l=1;this.v=new J(this,!0);Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.na.bind(this)});Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.qa.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.pa.bind(this)});this.ga=this.hasAttribute("pause-front-media");this.ha=this.hasAttribute("resume-next-media")};
f.attributeChangedCallback=function(a){switch(a){case "pause-front-media":this.ga=this.hasAttribute("pause-front-media");break;case "resume-next-media":this.ha=this.hasAttribute("resume-next-media")}};f.getFrame=function(a){if(0!=this.b)return this.frames[a-1]};f.gwdLoad=function(){};f.gwdIsLoaded=function(){return!0};f.goToFrame=function(a,b){this.stopRotation();0!=this.b&&(a>this.b?a=this.b:1>a&&(a=1),this.Z(a,b))};f.Z=function(a){this.a=a-1};
var P=function(a,b,c,d){if(null!=a.a){var e=K(a.a+L(b,a.l||1),a.l*Math.ceil(a.b/a.l));null!=d&&!d&&("forwards"==b&&e<a.a||"backwards"==b&&e>a.a)||a.goToFrame(e+1,c||"slide")}};f=O.prototype;f.goBackwards=function(a,b){return P(this,"backwards",a,b)};f.goForwards=function(a,b){return P(this,"forwards",a,b)};f.rotateOnce=function(a,b){this.v.play(a||0,b)};f.stopRotation=function(){this.v.stop()};f.na=function(){return 0<this.b?this.a+1:void 0};f.qa=function(){return this.l};f.pa=function(){return this.b};var Q=function(){};D(Q,O);
Q.prototype.createdCallback=function(){Q.C.createdCallback.call(this);this.N=!1;this.O=this.c=null;if(this.Y=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);this.o=C(0);var a=document.createElement("gwd-gesture");a.className="gesture";this.L=a;this.j=!1;this.f=null;this.ca=this.xa.bind(this);this.ea=this.za.bind(this);this.aa=this.va.bind(this);this.ba=this.wa.bind(this);this.da=this.ya.bind(this);this.V=this.sa.bind(this);this.ma=this.Ca.bind(this);this.la=this.Ba.bind(this);
this.ka=this.Aa.bind(this);this.X=this.ta.bind(this);this.fa=this.ua.bind(this);this.H=H.bind(null,"firstinteraction",this);this.R=!1;this.A=[];this.u=fa.bind(null,this,this.A);this.ia=this.ja=this.F=this.T=this.S=0;this.K=1;this.G=[];this.J=0;this.Da=.7;this.B=0;this.D=!1;this.P=C(0);this.I=C(0);this.g=null;this.h=this.$=-1;this.W=[];this.w=C(-1,-1);a="y"==this.getAttribute("swipe-axis");this.i=C(a?0:1,a?1:0);Object.defineProperty(this,"firstVisibleFrameIndex",{enumerable:!0,get:this.oa.bind(this)});
Object.defineProperty(this,"lastVisibleFrameIndex",{enumerable:!0,get:this.ra.bind(this)})};
Q.prototype.attachedCallback=function(){var a=this.L;a.addEventListener("pointerover",this.ea,!1);a.addEventListener("pointerout",this.ca,!1);a.addEventListener("pointermove",this.aa,!1);a.addEventListener("track",this.ma,!1);a.addEventListener("trackend",this.la,!1);a.addEventListener("tap",this.ka,!1);this.addEventListener("frametap",this.X,!1);this.addEventListener("swipefinished",this.U,!1);this.addEventListener("transitionend",this.u,!1);this.addEventListener("webkitTransitionEnd",this.u,!1);
if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=k(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}};
Q.prototype.detachedCallback=function(){var a=this.L;a.removeEventListener("pointerover",this.ea,!1);a.removeEventListener("pointerout",this.ca,!1);a.removeEventListener("pointermove",this.aa,!1);a.removeEventListener("track",this.ma,!1);a.removeEventListener("trackend",this.la,!1);a.removeEventListener("tap",this.ka,!1);this.removeEventListener("frametap",this.X,!1);this.removeEventListener("swipefinished",this.U,!1);this.removeEventListener("transitionend",this.u);this.removeEventListener("webkitTransitionEnd",
this.u)};
Q.prototype.attributeChangedCallback=function(a){Q.C.attributeChangedCallback.call(this,a);switch(a){case "images":this.frames=M(this.getAttribute("images"));R(this);S(this);break;case "scaling":N(this.frames,this.getAttribute("scaling"));break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":T(this);S(this);break;case "transition-duration":case "exit-urls":case "autoplay-duration":case "autoplay-step-interval":U(this);break;case "frame-width":case "frame-height":case "frame-snap-interval":case "num-frames-to-display":U(this);S(this);
break;case "disable-gesture":case "offset":case "start-frame":case "swipe-threshold-ratio":case "swipe-committed-threshold-ratio":S(this)}};
var U=function(a){var b=m(a,"num-frames-to-display",1),c=m(a,"frame-snap-interval",1),d=m(a,"transition-duration",600),e=m(a,"frame-width",-1),q=m(a,"frame-height",-1);var n=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"";var g=p(a,"autoplay-duration",3E3),t=p(a,"autoplay-step-interval",0);a.w.x=e;a.w.y=q;-1!=y(a.w,a.i)?b=-1:0<b&&c>b&&(c=b);a.W=n.split(/,/g);a.h=b;a.l=c;a.F=d;a.S=g;a.T=t},S=function(a){var b=C(a.clientWidth,a.clientHeight);a.g&&(b.y-=36,a.O.style.height=b.y+"px");var c=
a.i,d=z(c,m(a,"offset",0)),e=p(a,"swipe-threshold-ratio",.1),q=p(a,"swipe-committed-threshold-ratio",.5),n=a.h,g=a.w,g=C(-1==g.x?b.x:g.x,-1==g.y?b.y:g.y);if(a.hasAttribute("offset")){a:{var t=g.x;var l=g.y;b:switch(a.getAttribute("clamp-frame-size-to-image")){case "true":var u=!0;break b;case "false":u=!1;break b;default:u=!0}if(u){var w=a.hasAttribute("scaling")?a.getAttribute("scaling"):"contain";if((u="contain"==w)||"none"==w){var F=-1;w=-1;for(var ia=a.frameCount,I=0;I<ia;I++){var r=a.getFrame(I+
1);if("img"!=r.tagName.toLowerCase()||"gwd-image"!=r.getAttribute("is"))break a;var x=r,r=x.assetWidth,A=x.assetHeight;0<r&&0<A&&(u?r/A<t/l?(x=r/A*l,r=l):(x=t,r=A/r*t):(x=r,r=A),F=Math.max(F,x),w=Math.max(w,r))}t=-1!=F?Math.min(t,F):t;l=-1!=w?Math.min(l,w):l}}}1==c.x?g.x=t:g.y=l}1<n&&(l=z(c,n-1),l=C(l.x*d.x,l.y*d.y),n=B(C((b.x-l.x)/n,(b.y-l.y)/n),c),n.x&&(g.x=n.x),n.y&&(g.y=n.y));n=m(a,"start-frame",2<a.h?1+Math.ceil(a.h/2-1):1);t=a.hasAttribute("disable-gesture");l=B(C(g.x+d.x,g.y+d.y),c);u=1+2*
Math.floor((y(c,b)-y(c,g))/(2*y(c,l)));if(1>u||!isFinite(u))u=1;b=C((b.x-g.x)/2,(b.y-g.y)/2);0<a.h&&0==a.h%2&&(d=B(C(g.x+d.x,g.y+d.y),c),b.x-=.5*d.x,b.y-=.5*d.y,u+=1);a.I=g;a.P=b;a.K=u;a.B=y(l,a.i);a.j=t;a.ja=y(g,c)*e;a.ia=y(g,c)*q;e=B(b,C(c.y,c.x));for(d=0;d<a.b;d++)q=a.frames[d].style,q.left=e.x+"px",q.top=e.y+"px",q.width=g.x+"px",q.height=g.y+"px",e.x+=l.x,e.y+=l.y;a.o=C(0);a.c&&(V(a,0,0,0),c=B(b,c),a.c.style.left=c.x+"px",a.c.style.top=c.y+"px");a.a=null;a.goToFrame(n,"none")};f=Q.prototype;
f.gwdIsLoaded=function(){return this.N};f.gwdLoad=function(){if(!this.N&&!this.c){if(this.Y)var a=M(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;R(this)}};f.goBackwards=function(a,b){return Q.C.goBackwards.call(this,a,null!=b?b:!1)};f.goForwards=function(a,b){return Q.C.goForwards.call(this,a,null!=b?b:!1)};
f.Z=function(a,b){var c=a-1,c=c-c%this.l,c=c+Math.floor((this.l-1)/2);c>=this.b&&(c=this.b-1);a=c;null!=this.a&&this.a!=a&&(this.ga&&ga(this.frames[this.a]),this.ha&&ha(this.frames[a]));a=this.a;this.a=c;c=z(this.i,-this.B*this.a);V(this,"none"!=b?this.F:0,c.x,c.y);this.o=c;if(this.J)for(b=Math.floor((this.K-1)/2),c=0;c<this.K;c++){var d=this.a-b+c;if(!(0>d||d>=this.b||this.G[d]||(this.G[d]=!0,--this.J))){this.A.push("allframesviewed");break}}a!=this.a&&(W(this,this.a+1),this.A.push("frameshown"),
this.A.push("swipefinished"));this.R||this.u()};
var V=function(a,b,c,d){a.R=0<b;G(a.c,"transition","all "+b+"ms");G(a.c,"transform","translate3d("+c+"px,"+d+"px,0)")},R=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.g=null;a.c&&(a.c.removeEventListener("pageload",a.fa,!1),a.c.removeEventListener("mouseover",a.da,!0),a.c.removeEventListener("mouseout",a.ba,!0),a.c.removeEventListener("click",a.V,!0));for(var b=a.frames,c=document.createElement("div","gwd-page"),d,e=0;e<b.length;++e)d=b[e],G(d,"user-select","none"),d.classList.add("frame"),
c.appendChild(d);ba(c,c.gwdLoad.bind(c));a.c=c;c.className="container";a.c.addEventListener("pageload",a.fa,!1);a.c.addEventListener("mouseover",a.da,!0);a.c.addEventListener("mouseout",a.ba,!0);a.c.addEventListener("click",a.V,!0);N(a.frames,a.getAttribute("scaling"));a.b=a.frames.length;b=document.createElement("div");a.O=b;b.className="matte";b.appendChild(c);a.appendChild(a.O);a.appendChild(a.L)};Q.prototype.U=function(){G(this.c,"transition","all 0ms")};
Q.prototype.ua=function(a){a.target===this.c&&(this.N=!0,this.J=this.b,this.G=[],U(this),T(this),S(this),H("allframesloaded",this),this.hasAttribute("autoplay")&&this.v.play(this.S,"forwards",this.T),H("ready",this))};Q.prototype.rotateOnce=function(a,b){this.v.play(a||this.F,b)};
var Y=function(a,b){var c=a.b;if(c){var d=a.a;b=X(a,b);a.goToFrame(b+1);d!=b&&(0==b?H("reachleftend",a):b==c-1&&H("reachrightend",a))}},T=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.g;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.g=document.createElement("gwd-gallerynavigation"),a.g.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.g)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.g),a.g=null);a.g&&(v(a,"navigation-highlight",a.g,"highlight"),
v(a,"navigation-thumbnails",a.g,"use-thumbnails"))},X=function(a,b){var c=a.a;Math.abs(b)>a.ja&&(c=0>b?c+a.l:c-a.l);0>c?c=0:c>=a.b&&(c=a.b-1);return c},W=function(a,b){a.$!=b&&(a.$=b,H("frameactivated",a,{id:b||a.currentIndex}))};
Q.prototype.Ca=function(a){if(!this.j&&(this.H&&(this.H(),this.H=null),!this.D))if(this.stopRotation(),a=y(C(a.dx,a.dy),this.i),W(this,X(this,a)+1),Math.abs(a)>this.ia)Y(this,a),this.D=!0;else{if(0<a&&0===this.a||0>a&&this.a===this.b-1)a-=a*this.Da;V(this,0,this.o.x+this.i.x*a,this.o.y+this.i.y*a)}};Q.prototype.Ba=function(a){this.j||(this.D?this.D=!1:Y(this,y(C(a.dx,a.dy),this.i)))};
var Z=function(a,b){var c=a.getBoundingClientRect();b=C(b.clientX-c.left,b.clientY-c.top);var c=a.i,d=C(c.y,c.x),c=y(d,b),e=y(d,a.P),d=y(d,a.I);if(c<e||c>e+d)return null;c=a.i;b=y(c,b)-y(c,a.o)-y(c,a.P);c=Math.floor(b/a.B);return 0>c||c>=a.b||b%a.B>y(a.i,a.I)?null:c};f=Q.prototype;f.Aa=function(a){this.j||(this.stopRotation(),a=Z(this,a),null!=a&&H("frametap",this,{element:this.frames[a],id:a+1}))};
f.ta=function(a){(a=a.detail&&a.detail.id)&&(a=this.W[a-1])&&!H("frameexit",this,{url:a}).detail.handled&&window.open(a)};f.xa=function(){this.j||null==this.f||(H("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),this.f=null)};f.za=function(a){this.j||(a=Z(this,a),a!=this.f&&(null!=this.f&&H("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),null!=a&&H("framemouseover",this,{element:this.frames[a],id:1+a}),this.f=a))};
f.va=function(a){this.j||(a=Z(this,a),a!=this.f&&(null!=this.f&&H("framemouseout",this,{element:this.frames[this.f],id:1+this.f}),null!=a&&H("framemouseover",this,{element:this.frames[a],id:1+a}),this.f=a))};f.ya=function(a){this.j&&a.target.classList.contains("frame")&&H("framemouseover",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};f.wa=function(a){this.j&&a.target.classList.contains("frame")&&H("framemouseout",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};
f.sa=function(a){this.j&&a.target.classList.contains("frame")&&H("frametap",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};f.oa=function(){if(0<this.h&&0<this.b)return Math.max(1,1+this.a-Math.floor((this.h-1)/2))};f.ra=function(){if(0<this.h&&0<this.b)return Math.min(this.b,1+this.a-Math.floor((this.h-1)/2)+this.h-1)};document.registerElement("gwd-swipegallery",{prototype:Q.prototype});}).call(this);
