(function(){'use strict';var e;var k=function(a,b){a=parseInt(a.getAttribute("gwd-min-font-size-px"),12);isNaN(a)&&(a=b);return a},l=function(a,b){switch(a.getAttribute("gwd-fitting-truncate")){case "true":return!0;case "false":return!1;default:return b}};var p=/[^\s\xA0]/,r=function(a){return(a=q.exec(a||""))?parseFloat(a[1]):null},q=/^(\d+|\d*\.\d+)px$/i,t=/^(\d+|\d*\.\d+)em$/i;function w(){this.a=[];this.o=10;this.v=!1}
w.prototype.fit=function(a){var b=[];a.forEach(function(a){if(this.a.every(function(b){return b.element!=a})&&!a.hasAttribute("gwd-dont-fit")){x(a);var c=y(this,a);this.a.push(c);b.push(c)}},this);b.forEach(function(a){var b={originalFontSize:a.s,fittedFontSizePx:a.w,wasTruncated:null!=a.h};null!=a.h&&(b.originalInnerHTML=a.h);a=a.element;if(b){var c=document.createEvent("CustomEvent");c.initCustomEvent("gwdtextfitted",!0,!0,b)}else c=document.createEvent("Event"),c.initEvent("gwdtextfitted",!0,!0);
a.dispatchEvent(c)})};
var z=function(a,b){b.forEach(function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(c.element==a){c.element.style.fontSize=c.s;this.a.splice(b,1);break}}}.bind(a))},y=function(a,b){var c=window.getComputedStyle(b),d=r(c.fontSize)||24,g=k(b,a.o),h=l(b,a.v);a=b.style.fontSize;c=null;a:{for(var u=b.clientWidth,f=b.clientHeight;d>=g;d--)if(b.style.fontSize=""+d+"px",!(b.scrollHeight>f||b.scrollWidth>u)){g=d;break a}if(h){for(var c=b.innerHTML,h=b.textContent,d=h.length,m=1,v=0;10>v;v++){var n=
Math.floor((d+m)/2);b.textContent=h.slice(0,n)+"\u2026";b.scrollHeight>f||b.scrollWidth>u?d=n:m=n}b.innerHTML=h.slice(0,m)+"\u2026"}}return{element:b,s:a,w:g,h:c}},x=function(a){function b(a,c){a.hasAttribute("gwd-dont-fit")||Array.prototype.forEach.call(a.children,function(a){var d=window.getComputedStyle(a).fontSize,f=r(d);if(f)f!=c&&(d=f/c,a.style.fontSize=d+"em");else if(d=(f=t.exec(d||""))?parseFloat(f[1]):null)f=d*c;else return;b(a,f)})}var c=r(window.getComputedStyle(a).fontSize);null!=c&&
b(a,c)};var A=function(a){this.u=a;this.g=new WeakMap;this.j=new WeakMap};A.prototype.saveInitialText=function(a){for(var b=document.createNodeIterator(a,NodeFilter.SHOW_TEXT,null,!1),c=null,d;d=b.nextNode();)if(p.test(d.textContent)){c=d;break}if(c&&(b=c.parentNode,b!=a)){a.setAttribute("gwd-dont-fit","");for(c=b;c.parentNode!=a;)c=c.parentNode;this.g.set(a,{f:c,parent:b})}};
A.prototype.applyStylePreservation=function(a){if(this.g.get(a)){a.ownerDocument.compareDocumentPosition(a)&Node.DOCUMENT_POSITION_DISCONNECTED||B(this,a);var b=document.createElement("gwd-attached");a.appendChild(b);var c=function(){b.removeEventListener("attached",c);B(this,a);a.removeChild(b)}.bind(this);b.addEventListener("attached",c)}};
var B=function(a,b){var c=a.g.get(b),d=a.j.get(b)||{};if(c){c.f.style.display="none";b.insertBefore(c.f,b.firstChild);try{z(a.u,[b]);var g=getComputedStyle(c.parent);C.forEach(function(a){var c=g.getPropertyValue(a);!d.hasOwnProperty(a)&&c&&b.style.setProperty(a,c,"")});b.removeAttribute("gwd-dont-fit");a.u.fit([b])}finally{b.removeChild(c.f)}}};A.prototype.saveStyleOverride=function(a,b,c){var d=this.j.get(a)||{};d[b]=c;this.j.set(a,d)};var C="color font-family font-size font-style font-weight font-stretch text-align white-space".split(" ");var D=function(){};goog.inherits(D,HTMLElement);e=D.prototype;e.createdCallback=function(){this.c=new w;this.b=":not(*)";this.i=new A(this.c);this.C=this.B.bind(this);this.l=this.A.bind(this);document.addEventListener("pagetransitionstart",this.C);document.addEventListener("adinitialized",this.l);["fit-font-size-for-selector","gwd-fitting-truncate","gwd-min-font-size-px"].forEach(this.m,this)};
e.A=function(a){"gwd-doubleclick"==a.target.tagName.toLowerCase()&&(document.removeEventListener("adinitialized",this.l),this.fit(Array.prototype.slice.call(document.querySelectorAll(this.b))))};e.B=function(a){"gwd-pagedeck"==a.target.getAttribute("is").toLowerCase()&&this.fit(Array.prototype.slice.call(a.target.querySelectorAll(this.b)))};e.saveInitialText=function(a){this.i.saveInitialText(a)};e.applyStylePreservation=function(a){this.i.applyStylePreservation(a)};
e.saveStyleOverride=function(a,b,c){this.i.saveStyleOverride(a,b,c)};e.m=function(a){var b=this.getAttribute(a);switch(a){case "fit-font-size-for-selector":this.b=b||":not(*)";break;case "gwd-min-font-size-px":this.c.o=k(this,10);break;case "gwd-fitting-truncate":this.c.v=l(this,!1)}};e.fit=function(a){this.c.fit(a||Array.prototype.slice.call(document.querySelectorAll(this.b)))};e.attributeChangedCallback=function(a){this.m(a)};document.registerElement("gwd-text-helper",{prototype:D.prototype});}).call(this);
